# This is a basic workflow to help you get started with Actions

name: Scrape Vanguard Canada ETF in Dev

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: "true"
          go-version: "^1.15.5"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: GOARCH=amd64 GOOS=linux go build -o main main.go

      # Runs a set of commands using the runners shell
      - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r ./main.zip . -i main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Upload to s3 bucket
        run: aws s3 cp ./main.zip s3://tf-fund-lambdas-storage/dev/${{ secrets.DEV_FUNCTION_NAME }}/main.zip

      - name: Update lamdba function
        run: aws lambda update-function-code --function-name dev-${{ secrets.DEV_FUNCTION_NAME }} --zip-file fileb://main.zip
